using Lokad.OoxPdf.Tests;

return TestRunner.Run(
    PublicApiTests.PublicApiRejectsMissingInput,
    PublicApiTests.AutoDetectsPptxExtension,
    PublicApiTests.AutoDetectsDocxExtension,
    OoxmlTests.ParsesContentTypesAndRelationships,
    OoxmlTests.RejectsPackagePartPathTraversal,
    OoxmlTests.ResolvesRelationshipTargets,
    OoxmlTests.ConvertsCommonOfficeUnits,
    PdfWriterTests.WritesSingleBlankPagePdfStructure,
    PdfWriterTests.WritesMultipleBlankPagesWithPageSizes,
    PdfWriterTests.WritesDrawingOperators,
    PdfWriterTests.WritesEmbeddedTrueTypeFontObjects,
    PptxTests.PptxSyntheticTwoSlidesProducesTwoPdfPages,
    PptxTests.PptxSyntheticShapesProduceDrawingOperators,
    PptxTests.PptxSyntheticRotatedShapeProducesTransform,
    PptxTests.PptxSyntheticTextBoxEmbedsFontAndDrawsGlyphs,
    PptxTests.PptxSyntheticStyledTextProducesStyleOperators,
    PptxTests.PptxSyntheticThemeColorsAndFontsResolve,
    PptxTests.PptxSyntheticLayoutAndMasterShapesRender,
    PptxTests.PptxSyntheticInheritedPlaceholderTextIsSkipped,
    PptxTests.PptxSyntheticPngPictureRendersImageXObject,
    PptxTests.PptxSyntheticCroppedPictureUsesClipping,
    PptxTests.PptxSyntheticGroupedShapeAppliesTransform,
    PptxTests.PptxSyntheticTableRendersGridAndText,
    PptxTests.PptxUnsupportedFeaturesEmitDiagnostics,
    DocxTests.DocxSyntheticDocumentProducesOnePdfPage,
    DocxTests.DocxSyntheticParagraphRendersText,
    DocxTests.DocxSyntheticStylesApplyToParagraphText,
    DocxTests.DocxSyntheticParagraphsBreakAcrossPages,
    DocxTests.DocxSyntheticNumberingRendersListLabels,
    DocxTests.DocxSyntheticInlinePngRendersImageXObject,
    ImagingTests.JpegInfoReadsDimensions,
    FontTests.WindowsFontResolverFindsInstalledFonts,
    FontTests.OpenTypeParserMapsBasicLatinGlyphs);
