using System.Globalization;
using System.Xml.Linq;
using Lokad.OoxPdf.Ooxml;
using static Lokad.OoxPdf.Ooxml.OoxNamespaces;

namespace Lokad.OoxPdf.Pptx;

internal sealed partial class PptxSceneBuilder
{
    private static PptxSceneChartTitle ReadChartTitle(XDocument? chartXml, PptxTheme theme, PptxColorMap colorMap, IReadOnlyList<PptxSceneChartPlot> plots)
    {
        XElement? chart = chartXml?
            .Descendants(ChartNamespace + "chart")
            .FirstOrDefault();
        if (chart is null)
        {
            return EmptyChartTitle(IsAutoDeleted: null, IsAutoDeletedValue: "");
        }

        (bool? isAutoDeleted, string isAutoDeletedValue) = ReadOptionalOoxmlBooleanElementWithValue(chart, "autoTitleDeleted");
        return ReadChartTitleElement(chart.Element(ChartNamespace + "title"), theme, colorMap, isAutoDeleted, isAutoDeletedValue, plots);
    }

    private static PptxSceneChartTitle ReadChartTitleElement(XElement? title, PptxTheme theme, bool? isAutoDeleted, string isAutoDeletedValue, IReadOnlyList<PptxSceneChartPlot>? plots)
    {
        return ReadChartTitleElement(title, theme, PptxColorMap.Default, isAutoDeleted, isAutoDeletedValue, plots);
    }

    private static PptxSceneChartTitle ReadChartTitleElement(XElement? title, PptxTheme theme, PptxColorMap colorMap, bool? isAutoDeleted, string isAutoDeletedValue, IReadOnlyList<PptxSceneChartPlot>? plots)
    {
        if (title is null)
        {
            if (isAutoDeleted != false || plots is null)
            {
                return EmptyChartTitle(isAutoDeleted, isAutoDeletedValue);
            }

            string? inferredText = InferAutoChartTitleText(plots);
            return string.IsNullOrWhiteSpace(inferredText)
                ? EmptyChartTitle(isAutoDeleted, isAutoDeletedValue)
                : new PptxSceneChartTitle(
                    inferredText,
                    [new PptxSceneChartTextRun(inferredText, default)],
                    isAutoDeleted,
                    isAutoDeletedValue,
                    IsAutoGenerated: true,
                    Overlay: null,
                    OverlayValue: string.Empty,
                    default,
                    new PptxSceneChartShapeStyle(false, default, default, default, default, default, default, default, default),
                    default,
                    default);
        }

        (bool? overlay, string overlayValue) = ReadOptionalOoxmlBooleanElementWithValue(title, "overlay");
        XElement? textElement = title?.Element(ChartNamespace + "tx");
        string? text = ReadChartText(textElement, false);
        var runs = ReadChartTextRuns(textElement, theme, colorMap);
        bool isAutoGenerated = false;
        if (string.IsNullOrWhiteSpace(text) && isAutoDeleted == false && plots is not null)
        {
            string? inferredText = InferAutoChartTitleText(plots);
            if (!string.IsNullOrWhiteSpace(inferredText))
            {
                text = inferredText;
                runs = [new PptxSceneChartTextRun(inferredText, default)];
                isAutoGenerated = true;
            }
        }

        return new PptxSceneChartTitle(
            string.IsNullOrWhiteSpace(text) ? null : text,
            runs,
            isAutoDeleted,
            isAutoDeletedValue,
            IsAutoGenerated: isAutoGenerated,
            overlay,
            overlayValue,
            ReadChartManualLayout(title),
            ReadChartShapeStyle(title?.Element(ChartNamespace + "spPr"), theme, colorMap),
            ReadChartTextBodyProperties(title),
            ReadChartTextStyleOverride(title, theme, colorMap));

        string? InferAutoChartTitleText(IReadOnlyList<PptxSceneChartPlot> plots)
        {
            IReadOnlyList<PptxSceneChartSeries> series = plots
                .SelectMany(plot => plot.Series)
                .ToArray();
            if (series.Count != 1)
            {
                return null;
            }

            string? name = series[0].Name?.Trim();
            return string.IsNullOrWhiteSpace(name) ? null : name;
        }
    }

    private static PptxSceneChartTitle EmptyChartTitle(bool? IsAutoDeleted, string IsAutoDeletedValue)
    {
        return new PptxSceneChartTitle(
            null,
            [],
            IsAutoDeleted,
            IsAutoDeletedValue,
            IsAutoGenerated: false,
            Overlay: null,
            OverlayValue: string.Empty,
            default,
            new PptxSceneChartShapeStyle(false, default, default, default, default, default, default, default, default),
            default,
            default);
    }

    internal static PptxSceneChartLegend ReadChartLegend(XDocument? chartXml, PptxTheme theme, PptxColorMap colorMap)
    {
        XElement? legend = chartXml?
            .Descendants(ChartNamespace + "legend")
            .FirstOrDefault();
        if (legend is null)
        {
            return new PptxSceneChartLegend(
                PptxSceneChartLegendPosition.Right,
                "r",
                Overlay: null,
                OverlayValue: string.Empty,
                IsDefined: false,
                IsDeleted: null,
                IsDeletedValue: string.Empty,
                default,
                new PptxSceneChartShapeStyle(false, default, default, default, default, default, default, default, default),
                default,
                default);
        }

        string position = ReadOptionalChartValueAttribute(legend.Element(ChartNamespace + "legendPos")) ?? "r";
        (bool? overlay, string overlayValue) = ReadOptionalOoxmlBooleanElementWithValue(legend, "overlay");
        (bool? isDeleted, string isDeletedValue) = ReadOptionalOoxmlBooleanElementWithValue(legend, "delete");
        return new PptxSceneChartLegend(
            ParseChartLegendPosition(position),
            position,
            overlay,
            overlayValue,
            IsDefined: true,
            isDeleted,
            isDeletedValue,
            ReadChartManualLayout(legend),
            ReadChartShapeStyle(legend.Element(ChartNamespace + "spPr"), theme, colorMap),
            ReadChartTextBodyProperties(legend),
            ReadChartTextStyleOverride(legend, theme, colorMap));
    }
}
