using System.Globalization;
using System.Text;
using System.Xml.Linq;
using Lokad.OoxPdf.Diagnostics;
using Lokad.OoxPdf.Fonts;
using Lokad.OoxPdf.Ooxml;
using static Lokad.OoxPdf.Ooxml.OoxNamespaces;
using Lokad.OoxPdf.Pdf;

namespace Lokad.OoxPdf.Pptx;

internal sealed partial class PptxRenderer
{
    private static void RenderChartTitle(PptxDocument document, PptxTheme theme, PptxColorMap colorMap, PdfGraphicsBuilder graphics, ShapeBounds bounds, XDocument chartXml, PptxSceneChart? sceneChart, ChartWorkbookData? workbook, bool plotVisibleOnly, PresentationFontResolver fontResolver, List<PdfFontResource> chartFonts, PptxRenderContext context, List<PdfLinkAnnotation> linkAnnotations, HashSet<string> reportedHyperlinkIds, Action<OoxPdfDiagnostic>? diagnosticSink = null)
    {
        string? title = ReadSceneOrXmlChartTitleText(sceneChart, chartXml);
        if (string.IsNullOrWhiteSpace(title))
        {
            return;
        }

        ChartFrameBox frame = GetChartFrameBox(document, bounds);
        double x = frame.X;
        double y = frame.Y;
        double width = frame.Width;
        double height = frame.Height;
        bool titleManualLayoutApplied = false;
        if (sceneChart?.Title.Layout.HasLayout == true &&
            TryBuildManualLayoutBox(sceneChart.Title.Layout, frame, new ChartLayoutBox(frame.X, frame.Y, frame.Width, frame.Height), out ChartLayoutBox titleBox, true, false))
        {
            x = titleBox.X;
            y = titleBox.Y;
            width = titleBox.Width;
            height = titleBox.Height;
            titleManualLayoutApplied = true;
        }

        bool isAutoTitle = IsAutoGeneratedChartTitle(sceneChart);
        ChartTextStyle style = ReadSceneOrXmlChartTitleTextStyle(theme, colorMap, sceneChart, chartXml, isAutoTitle);
        double fontSize = style.FontSize;
        double titleBaselineRatio = !titleManualLayoutApplied && HasSceneOrXmlPolarChart(sceneChart, chartXml)
            ? PptxChartMetricRules.PolarTitleBaselineYRatio
            : PptxChartMetricRules.TitleBaselineYRatio;
        double fallbackBaselineY = y + height * titleBaselineRatio;
        double baselineY = titleManualLayoutApplied
            ? fallbackBaselineY
            : ResolveChartTitleBaselineY(document, theme, colorMap, bounds, chartXml, sceneChart, workbook, plotVisibleOnly, fallbackBaselineY, fontSize, fontResolver);
        RenderChartShapeStyle(graphics, x, y, width, height, ReadSceneOrXmlChartTitleShapeStyle(theme, colorMap, sceneChart, chartXml));
        double titleX = x + width * PptxChartMetricRules.TitleXInsetRatio;
        double titleWidth = width * PptxChartMetricRules.TitleWidthRatio;
        double titleHeight = fontSize * PptxChartMetricRules.TitleHeightFactor;
        var runs = new List<TextRun>();
        List<ChartTextRunLink>? titleLinks = sceneChart?.Relationships is null ? null : new List<ChartTextRunLink>();
        AddChartRichTextRuns(
            runs,
            ReadSceneOrXmlChartTitleTextRuns(theme, colorMap, sceneChart, chartXml),
            title.Trim(),
            titleX,
            baselineY,
            titleWidth,
            titleHeight,
            x,
            y,
            width,
            height,
            style,
            TextAlignment.Center,
            fontResolver,
            titleLinks);
        RenderedFonts titleFonts = RenderChartTextRuns(runs, graphics, chartFonts, "CT", fontResolver, diagnosticSink);
        if (titleLinks is not null && sceneChart?.Relationships is not null)
        {
            foreach (ChartTextRunLink titleLink in titleLinks)
            {
                AddChartTextRunHyperlinkAnnotation(titleLink, sceneChart.Relationships, context, sceneChart.TargetPartName, linkAnnotations, reportedHyperlinkIds, titleFonts.Fonts);
            }
        }
    }

    private static ChartShapeStyle ReadSceneOrXmlChartTitleShapeStyle(PptxTheme theme, PptxColorMap colorMap, PptxSceneChart? sceneChart, XDocument chartXml)
    {
        return sceneChart is null
            ? ToChartShapeStyle(PptxSceneBuilder.ReadChartShapeStyle(chartXml.Descendants(ChartNamespace + "title").FirstOrDefault()?.Element(ChartNamespace + "spPr"), theme, colorMap))
            : ToChartShapeStyle(sceneChart.Title.ShapeStyle);
    }

    private static void RenderManualChartAxisTitles(
        PptxDocument document,
        PptxTheme theme,
        PptxColorMap colorMap,
        PdfGraphicsBuilder graphics,
        ShapeBounds bounds,
        XDocument chartXml,
        PptxSceneChart? sceneChart,
        PresentationFontResolver fontResolver,
        Action<OoxPdfDiagnostic>? diagnosticSink,
        string? chartPartName,
        int slideIndex,
        bool emitDefaultLayoutDiagnostics,
        List<PdfFontResource> chartFonts,
        PptxRenderContext context,
        List<PdfLinkAnnotation> linkAnnotations,
        HashSet<string> reportedHyperlinkIds)
    {
        ChartFrameBox frame = GetChartFrameBox(document, bounds);
        if (sceneChart is not null)
        {
            foreach (PptxSceneChartAxis axis in sceneChart.Axes)
            {
                if (!string.IsNullOrWhiteSpace(axis.Title.Text) && !axis.Title.Layout.HasLayout)
                {
                    if (emitDefaultLayoutDiagnostics)
                    {
                        EmitChartDiagnostic(diagnosticSink, "PPTX_UNSUPPORTED_CHART_AXIS_TITLE_LAYOUT", OoxPdfSeverity.Warning, "Default-placement chart axis titles are not rendered until the Office axis-title layout model is implemented.", chartPartName, slideIndex, "Ignored");
                    }

                    continue;
                }

                RenderManualChartAxisTitle(
                    theme,
                    graphics,
                    frame,
                    axis.Title.Text,
                    ToChartTextRuns(axis.Title.TextRuns),
                    axis.Title.Layout,
                    ToChartShapeStyle(axis.Title.ShapeStyle),
                    axis.Title.TextBodyProperties,
                    ToChartTextStyleOverride(PptxSceneBuilder.ResolveChartElementTextStyleOverride(sceneChart, axis.Title.TextStyle, GetChartAxisStyleRole(axis.AxisKind))),
                    ChartTextStyleOverride.Empty,
                    ChartTextStyleOverride.Empty,
                    fontResolver, chartFonts, context, sceneChart.Relationships, linkAnnotations, reportedHyperlinkIds, diagnosticSink);
            }

            return;
        }

        foreach (XElement axis in ReadChartAxisElements(chartXml))
        {
            XElement? title = axis.Element(ChartNamespace + "title");
            if (title is null)
            {
                continue;
            }

            string? text = PptxSceneBuilder.ReadChartText(title.Element(ChartNamespace + "tx"), trimLiteral: true);
            if (string.IsNullOrWhiteSpace(text))
            {
                continue;
            }

            PptxSceneChartManualLayout layout = PptxSceneBuilder.ReadChartManualLayout(title);
            if (!layout.HasLayout)
            {
                if (emitDefaultLayoutDiagnostics)
                {
                    EmitChartDiagnostic(diagnosticSink, "PPTX_UNSUPPORTED_CHART_AXIS_TITLE_LAYOUT", OoxPdfSeverity.Warning, "Default-placement chart axis titles are not rendered until the Office axis-title layout model is implemented.", chartPartName, slideIndex, "Ignored");
                }

                continue;
            }

            RenderManualChartAxisTitle(
                theme,
                graphics,
                frame,
                text,
                ToChartTextRuns(PptxSceneBuilder.ReadChartTextRuns(title.Element(ChartNamespace + "tx"), theme, colorMap)),
                layout,
                ToChartShapeStyle(PptxSceneBuilder.ReadChartShapeStyle(title.Element(ChartNamespace + "spPr"), theme, colorMap)),
                PptxSceneBuilder.ReadChartTextBodyProperties(title),
                ToChartTextStyleOverride(PptxSceneBuilder.ReadChartTextStyleOverride(chartXml.Root, theme, colorMap)),
                ChartTextStyleOverride.Empty,
                ToChartTextStyleOverride(PptxSceneBuilder.ReadChartTextStyleOverride(title, theme, colorMap)),
                fontResolver, chartFonts, context, null, linkAnnotations, reportedHyperlinkIds, diagnosticSink);
        }

    }

    private static void RenderDefaultChartAxisTitles(
        PptxTheme theme,
        PptxColorMap colorMap,
        PdfGraphicsBuilder graphics,
        ChartLayout layout,
        XDocument chartXml,
        PptxSceneChart? sceneChart,
        PresentationFontResolver fontResolver,
        List<PdfFontResource> chartFonts,
        PptxRenderContext context,
        List<PdfLinkAnnotation> linkAnnotations,
        HashSet<string> reportedHyperlinkIds,
        Action<OoxPdfDiagnostic>? diagnosticSink = null)
    {
        if (sceneChart is not null)
        {
            foreach (PptxSceneChartAxis axis in sceneChart.Axes)
            {
                if (axis.IsDeleted == true ||
                    string.IsNullOrWhiteSpace(axis.Title.Text) ||
                    axis.Title.Layout.HasLayout)
                {
                    continue;
                }

                RenderDefaultChartAxisTitle(
                    theme,
                    graphics,
                    layout,
                    axis.Title.Text,
                    ToChartTextRuns(axis.Title.TextRuns),
                    axis.AxisKind,
                    axis.PositionKind,
                    ToChartShapeStyle(axis.Title.ShapeStyle),
                    axis.Title.TextBodyProperties,
                    ToChartTextStyleOverride(PptxSceneBuilder.ResolveChartElementTextStyleOverride(sceneChart, axis.Title.TextStyle, GetChartAxisStyleRole(axis.AxisKind))),
                    ChartTextStyleOverride.Empty,
                    ChartTextStyleOverride.Empty,
                    fontResolver, chartFonts, context, sceneChart.Relationships, linkAnnotations, reportedHyperlinkIds, diagnosticSink);
            }

            return;
        }

        foreach (XElement axis in ReadChartAxisElements(chartXml))
        {
            XElement? title = axis.Element(ChartNamespace + "title");
            string? text = PptxSceneBuilder.ReadChartText(title?.Element(ChartNamespace + "tx"), trimLiteral: true);
            if (title is null ||
                string.IsNullOrWhiteSpace(text) ||
                PptxSceneBuilder.ReadChartManualLayout(title).HasLayout)
            {
                continue;
            }

            RenderDefaultChartAxisTitle(
                theme,
                graphics,
                layout,
                text,
                ToChartTextRuns(PptxSceneBuilder.ReadChartTextRuns(title.Element(ChartNamespace + "tx"), theme, colorMap)),
                PptxSceneBuilder.ParseChartAxisKind(axis.Name.LocalName),
                PptxSceneBuilder.ParseChartAxisPosition(PptxSceneBuilder.ReadChartElementValue(axis, "axPos")),
                ToChartShapeStyle(PptxSceneBuilder.ReadChartShapeStyle(title.Element(ChartNamespace + "spPr"), theme, colorMap)),
                PptxSceneBuilder.ReadChartTextBodyProperties(title),
                ToChartTextStyleOverride(PptxSceneBuilder.ReadChartTextStyleOverride(chartXml.Root, theme, colorMap)),
                ChartTextStyleOverride.Empty,
                ToChartTextStyleOverride(PptxSceneBuilder.ReadChartTextStyleOverride(title, theme, colorMap)),
                fontResolver, chartFonts, context, null, linkAnnotations, reportedHyperlinkIds, diagnosticSink);
        }

            return;
    }

    private static void EmitUnrenderedDefaultChartAxisTitleDiagnostics(
        XDocument chartXml,
        PptxSceneChart? sceneChart,
        Action<OoxPdfDiagnostic>? diagnosticSink,
        string? chartPartName,
        int slideIndex)
    {
        if (diagnosticSink is null)
        {
            return;
        }

        if (sceneChart is not null)
        {
            foreach (PptxSceneChartAxis axis in sceneChart.Axes)
            {
                if (axis.IsDeleted == true ||
                    string.IsNullOrWhiteSpace(axis.Title.Text) ||
                    axis.Title.Layout.HasLayout ||
                    IsRenderableDefaultChartAxisTitle(axis.AxisKind, axis.PositionKind))
                {
                    continue;
                }

                EmitChartDiagnostic(diagnosticSink, "PPTX_UNSUPPORTED_CHART_AXIS_TITLE_AXIS_POSITION", OoxPdfSeverity.Warning, "Default-placement chart axis title has an unsupported or missing axis kind/position.", chartPartName, slideIndex, "Ignored");
            }

            return;
        }

        foreach (XElement axis in ReadChartAxisElements(chartXml))
        {
            XElement? title = axis.Element(ChartNamespace + "title");
            string? text = PptxSceneBuilder.ReadChartText(title?.Element(ChartNamespace + "tx"), trimLiteral: true);
            if (title is null ||
                string.IsNullOrWhiteSpace(text) ||
                PptxSceneBuilder.ReadChartManualLayout(title).HasLayout ||
                IsRenderableDefaultChartAxisTitle(
                    PptxSceneBuilder.ParseChartAxisKind(axis.Name.LocalName),
                    PptxSceneBuilder.ParseChartAxisPosition(PptxSceneBuilder.ReadChartElementValue(axis, "axPos"))))
            {
                continue;
            }

            EmitChartDiagnostic(diagnosticSink, "PPTX_UNSUPPORTED_CHART_AXIS_TITLE_AXIS_POSITION", OoxPdfSeverity.Warning, "Default-placement chart axis title has an unsupported or missing axis kind/position.", chartPartName, slideIndex, "Ignored");
        }
    }

    private static void RenderDefaultChartAxisTitle(
        PptxTheme theme,
        PdfGraphicsBuilder graphics,
        ChartLayout layout,
        string? text,
        IReadOnlyList<ChartTextRunOverride> textRuns,
        PptxSceneChartAxisKind axisKind,
        PptxSceneChartAxisPosition positionKind,
        ChartShapeStyle shapeStyle,
        PptxSceneChartTextBodyProperties textBodyProperties,
        ChartTextStyleOverride chartTextStyle,
        ChartTextStyleOverride chartStyleRoleTextStyle,
        ChartTextStyleOverride titleTextStyle,
        PresentationFontResolver fontResolver,
        List<PdfFontResource> chartFonts,
        PptxRenderContext context,
        IReadOnlyDictionary<string, OoxRelationship>? chartRelationships,
        List<PdfLinkAnnotation> linkAnnotations,
        HashSet<string> reportedHyperlinkIds,
        Action<OoxPdfDiagnostic>? diagnosticSink = null)
    {
        if (string.IsNullOrWhiteSpace(text))
        {
            return;
        }

        ChartTextStyle style = CreateDefaultChartTextStyle(theme, fallbackFontSize: PptxChartMetricRules.TitleFallbackFontSize);
        style = style.Merge(chartTextStyle);
        style = style.Merge(chartStyleRoleTextStyle);
        style = style.Merge(titleTextStyle);
        string trimmed = text.Trim();
        double titleHeight = style.FontSize * PptxChartMetricRules.TitleHeightFactor;
        var textMeasurer = new ChartTextMeasurer(fontResolver);
        double textWidth = Math.Max(style.FontSize, textMeasurer.Measure(trimmed, style));
        if (!IsRenderableDefaultChartAxisTitle(axisKind, positionKind))
        {
            return;
        }

        if (positionKind is PptxSceneChartAxisPosition.Bottom or PptxSceneChartAxisPosition.Top)
        {
            RenderDefaultHorizontalChartAxisTitle(graphics, layout, trimmed, textRuns, style, shapeStyle, titleHeight, textWidth, positionKind, fontResolver, chartFonts, context, chartRelationships, linkAnnotations, reportedHyperlinkIds, diagnosticSink);
        }
        else if (positionKind is PptxSceneChartAxisPosition.Left or PptxSceneChartAxisPosition.Right)
        {
            RenderDefaultVerticalChartAxisTitle(graphics, layout, trimmed, textRuns, style, shapeStyle, titleHeight, textWidth, positionKind, fontResolver, chartFonts, context, chartRelationships, linkAnnotations, reportedHyperlinkIds, diagnosticSink);
        }
    }

    private static bool IsRenderableDefaultChartAxisTitle(PptxSceneChartAxisKind axisKind, PptxSceneChartAxisPosition positionKind)
    {
        return positionKind switch
        {
            PptxSceneChartAxisPosition.Bottom or PptxSceneChartAxisPosition.Top =>
                axisKind is PptxSceneChartAxisKind.Category or PptxSceneChartAxisKind.Date or PptxSceneChartAxisKind.Series or PptxSceneChartAxisKind.Value,
            PptxSceneChartAxisPosition.Left or PptxSceneChartAxisPosition.Right =>
                axisKind is PptxSceneChartAxisKind.Value or PptxSceneChartAxisKind.Category or PptxSceneChartAxisKind.Date,
            _ => false
        };
    }

    private static string GetChartAxisStyleRole(PptxSceneChartAxisKind axisKind)
    {
        return axisKind switch
        {
            PptxSceneChartAxisKind.Value => "valueAxis",
            PptxSceneChartAxisKind.Category or PptxSceneChartAxisKind.Date or PptxSceneChartAxisKind.Series => "categoryAxis",
            _ => string.Empty
        };
    }

    private static void RenderDefaultHorizontalChartAxisTitle(
        PdfGraphicsBuilder graphics,
        ChartLayout layout,
        string text,
        IReadOnlyList<ChartTextRunOverride> textRuns,
        ChartTextStyle style,
        ChartShapeStyle shapeStyle,
        double titleHeight,
        double textWidth,
        PptxSceneChartAxisPosition positionKind,
        PresentationFontResolver? fontResolver,
        List<PdfFontResource> chartFonts,
        PptxRenderContext context,
        IReadOnlyDictionary<string, OoxRelationship>? chartRelationships,
        List<PdfLinkAnnotation> linkAnnotations,
        HashSet<string> reportedHyperlinkIds,
        Action<OoxPdfDiagnostic>? diagnosticSink = null)
    {
        ChartFrameBox frame = layout.Frame;
        ChartPlotBox plotBox = layout.PlotBox;
        double titleX = plotBox.X + plotBox.Width / 2d - textWidth / 2d;
        double baselineY;
        double boxY;
        if (positionKind == PptxSceneChartAxisPosition.Top)
        {
            double topReserve = Math.Max(0d, frame.Y + frame.Height - plotBox.Y - plotBox.Height);
            baselineY = plotBox.Y + plotBox.Height + topReserve * PptxChartMetricRules.DefaultAxisTitleTopBandBaselineRatio;
            boxY = Math.Max(plotBox.Y + plotBox.Height, baselineY - titleHeight);
        }
        else
        {
            double bottomReserve = Math.Max(0d, plotBox.Y - frame.Y);
            baselineY = frame.Y + bottomReserve * PptxChartMetricRules.DefaultAxisTitleBandBaselineRatio;
            boxY = Math.Max(frame.Y, baselineY - titleHeight);
        }

        double boxX = Math.Max(frame.X, titleX - style.FontSize * 0.5d);
        double boxWidth = Math.Min(frame.X + frame.Width - boxX, textWidth + style.FontSize);
        RenderChartShapeStyle(graphics, boxX, boxY, boxWidth, titleHeight, shapeStyle);
        var runs = new List<TextRun>();
        List<ChartTextRunLink>? axisLinks = chartRelationships is null ? null : new List<ChartTextRunLink>();
        AddChartRichTextRuns(
            runs,
            textRuns,
            text,
            titleX,
            baselineY,
            textWidth,
            titleHeight,
            frame.X,
            frame.Y,
            frame.Width,
            frame.Height,
            style,
            TextAlignment.Center,
            fontResolver,
            axisLinks);
        RenderedFonts axisFonts = RenderChartTextRuns(runs, graphics, chartFonts, "CAT", fontResolver, diagnosticSink);
        AddChartTextRunHyperlinkAnnotations(axisLinks, chartRelationships, context, axisFonts, linkAnnotations, reportedHyperlinkIds);
    }

    private static void RenderDefaultVerticalChartAxisTitle(
        PdfGraphicsBuilder graphics,
        ChartLayout layout,
        string text,
        IReadOnlyList<ChartTextRunOverride> textRuns,
        ChartTextStyle style,
        ChartShapeStyle shapeStyle,
        double titleHeight,
        double textWidth,
        PptxSceneChartAxisPosition positionKind,
        PresentationFontResolver? fontResolver,
        List<PdfFontResource> chartFonts,
        PptxRenderContext context,
        IReadOnlyDictionary<string, OoxRelationship>? chartRelationships,
        List<PdfLinkAnnotation> linkAnnotations,
        HashSet<string> reportedHyperlinkIds,
        Action<OoxPdfDiagnostic>? diagnosticSink = null)
    {
        ChartFrameBox frame = layout.Frame;
        ChartPlotBox plotBox = layout.PlotBox;
        bool rightSide = positionKind == PptxSceneChartAxisPosition.Right;
        double sideReserve = rightSide
            ? Math.Max(0d, frame.X + frame.Width - plotBox.X - plotBox.Width)
            : Math.Max(0d, plotBox.X - frame.X);
        double sideBaselineRatio = rightSide
            ? PptxChartMetricRules.DefaultAxisTitleRightSideBaselineRatio
            : PptxChartMetricRules.DefaultAxisTitleLeftSideBaselineRatio;
        double baselineX = rightSide
            ? plotBox.X + plotBox.Width + sideReserve * sideBaselineRatio
            : frame.X + sideReserve * sideBaselineRatio;
        double baselineY = plotBox.Y + plotBox.Height / 2d
            - textWidth * PptxChartMetricRules.DefaultAxisTitleSideBaselineRatio;
        double boxX = Math.Max(frame.X, Math.Min(frame.X + frame.Width - titleHeight, baselineX - titleHeight * 0.5d));
        double boxY = Math.Max(frame.Y, Math.Min(frame.Y + frame.Height - textWidth, baselineY));
        RenderChartShapeStyle(graphics, boxX, boxY, titleHeight, textWidth, shapeStyle);
        var runs = new List<TextRun>();
        List<ChartTextRunLink>? axisLinks = chartRelationships is null ? null : new List<ChartTextRunLink>();
        AddChartRichTextRuns(
            runs,
            textRuns,
            text,
            baselineX,
            baselineY,
            textWidth,
            titleHeight,
            frame.X,
            frame.Y,
            frame.Width,
            frame.Height,
            style,
            TextAlignment.Left,
            fontResolver,
            axisLinks);
        double rotation = -90d;
        for (int i = 0; i < runs.Count; i++)
        {
            TextRun run = runs[i];
            runs[i] = run with
            {
                RotationDegrees = rotation,
                RotationCenterX = run.X,
                RotationCenterY = run.Y
            };
        }

        if (axisLinks is not null)
        {
            for (int linkIndex = 0; linkIndex < axisLinks.Count; linkIndex++)
            {
                ChartTextRunLink axisLink = axisLinks[linkIndex];
                TextRun linkedRun = axisLink.Run;
                axisLinks[linkIndex] = axisLink with
                {
                    Run = linkedRun with
                    {
                        RotationDegrees = rotation,
                        RotationCenterX = linkedRun.X,
                        RotationCenterY = linkedRun.Y
                    }
                };
            }
        }

        RenderedFonts axisFonts = RenderChartTextRuns(runs, graphics, chartFonts, "CAT", fontResolver, diagnosticSink);
        AddChartTextRunHyperlinkAnnotations(axisLinks, chartRelationships, context, axisFonts, linkAnnotations, reportedHyperlinkIds);
    }

    private static void RenderManualChartAxisTitle(
        PptxTheme theme,
        PdfGraphicsBuilder graphics,
        ChartFrameBox frame,
        string? text,
        IReadOnlyList<ChartTextRunOverride> textRuns,
        PptxSceneChartManualLayout layout,
        ChartShapeStyle shapeStyle,
        PptxSceneChartTextBodyProperties textBodyProperties,
        ChartTextStyleOverride chartTextStyle,
        ChartTextStyleOverride chartStyleRoleTextStyle,
        ChartTextStyleOverride titleTextStyle,
        PresentationFontResolver? fontResolver,
        List<PdfFontResource> chartFonts,
        PptxRenderContext context,
        IReadOnlyDictionary<string, OoxRelationship>? chartRelationships,
        List<PdfLinkAnnotation> linkAnnotations,
        HashSet<string> reportedHyperlinkIds,
        Action<OoxPdfDiagnostic>? diagnosticSink = null)
    {
        if (string.IsNullOrWhiteSpace(text) ||
            !TryBuildManualLayoutBox(layout, frame, new ChartLayoutBox(frame.X, frame.Y, frame.Width, frame.Height), out ChartLayoutBox titleBox, true, false))
        {
            return;
        }

        ChartTextStyle style = CreateDefaultChartTextStyle(theme, fallbackFontSize: PptxChartMetricRules.TitleFallbackFontSize);
        style = style.Merge(chartTextStyle);
        style = style.Merge(chartStyleRoleTextStyle);
        style = style.Merge(titleTextStyle);
        RenderChartShapeStyle(graphics, titleBox.X, titleBox.Y, titleBox.Width, titleBox.Height, shapeStyle);
        double titleHeight = style.FontSize * PptxChartMetricRules.TitleHeightFactor;
        double baselineY = titleBox.Y + titleBox.Height * PptxChartMetricRules.TitleBaselineYRatio;
        var runs = new List<TextRun>();
        List<ChartTextRunLink>? axisLinks = chartRelationships is null ? null : new List<ChartTextRunLink>();
        AddChartRichTextRuns(
            runs,
            textRuns,
            text.Trim(),
            titleBox.X + titleBox.Width * PptxChartMetricRules.TitleXInsetRatio,
            baselineY,
            titleBox.Width * PptxChartMetricRules.TitleWidthRatio,
            titleHeight,
            titleBox.X,
            titleBox.Y,
            titleBox.Width,
            titleBox.Height,
            style,
            TextAlignment.Center,
            fontResolver,
            axisLinks);
        RenderedFonts axisFonts = RenderChartTextRuns(runs, graphics, chartFonts, "CAT", fontResolver, diagnosticSink);
        AddChartTextRunHyperlinkAnnotations(axisLinks, chartRelationships, context, axisFonts, linkAnnotations, reportedHyperlinkIds);
    }

    private static IReadOnlyList<XElement> ReadChartAxisElements(XDocument chartXml)
    {
        XElement? plotArea = chartXml
            .Descendants(ChartNamespace + "plotArea")
            .FirstOrDefault();
        return plotArea is null
            ? []
            : plotArea.Elements()
                .Where(element => element.Name.Namespace == ChartNamespace && element.Name.LocalName.EndsWith("Ax", StringComparison.Ordinal))
                .ToArray();
    }

    private static ChartAxisTitleReserveSides ReadSceneOrXmlDefaultAxisTitleReserveSides(PptxSceneChart? sceneChart, XDocument chartXml)
    {
        var reserveSides = new ChartAxisTitleReserveSides();
        if (sceneChart is not null)
        {
            foreach (PptxSceneChartAxis axis in sceneChart.Axes)
            {
                if (axis.IsDeleted == true ||
                    string.IsNullOrWhiteSpace(axis.Title.Text) ||
                    axis.Title.Layout.HasLayout ||
                    !IsRenderableDefaultChartAxisTitle(axis.AxisKind, axis.PositionKind))
                {
                    continue;
                }

                reserveSides = reserveSides.With(axis.PositionKind);
            }

            return reserveSides;
        }

        foreach (XElement axis in ReadChartAxisElements(chartXml))
        {
            XElement? title = axis.Element(ChartNamespace + "title");
            string? text = PptxSceneBuilder.ReadChartText(title?.Element(ChartNamespace + "tx"), trimLiteral: true);
            PptxSceneChartAxisKind axisKind = PptxSceneBuilder.ParseChartAxisKind(axis.Name.LocalName);
            PptxSceneChartAxisPosition positionKind = PptxSceneBuilder.ParseChartAxisPosition(PptxSceneBuilder.ReadChartElementValue(axis, "axPos"));
            if (title is null ||
                string.IsNullOrWhiteSpace(text) ||
                PptxSceneBuilder.ReadChartManualLayout(title).HasLayout ||
                !IsRenderableDefaultChartAxisTitle(axisKind, positionKind))
            {
                continue;
            }

            reserveSides = reserveSides.With(positionKind);
        }

        return reserveSides;
    }

    private static bool HasSceneOrXmlPolarChart(PptxSceneChart? sceneChart, XDocument chartXml)
    {
        return sceneChart is not null
            ? sceneChart.Plots.Any(plot =>
                plot.PlotKind is PptxSceneChartPlotKind.Pie or
                    PptxSceneChartPlotKind.Doughnut or
                    PptxSceneChartPlotKind.Radar)
            : HasPolarChart(chartXml);
    }

    private static bool HasPolarChart(XDocument chartXml)
    {
        return ReadChartPlotElements(chartXml, PptxSceneChartPlotKind.Pie).Any() ||
            ReadChartPlotElements(chartXml, PptxSceneChartPlotKind.Doughnut).Any() ||
            ReadChartPlotElements(chartXml, PptxSceneChartPlotKind.Radar).Any();
    }

    private static double ResolveChartTitleBaselineY(PptxDocument document, PptxTheme theme, PptxColorMap colorMap, ShapeBounds bounds, XDocument chartXml, PptxSceneChart? sceneChart, ChartWorkbookData? workbook, bool plotVisibleOnly, double fallbackBaselineY, double fontSize, PresentationFontResolver? fontResolver)
    {
        XElement? barChart = ReadSceneOrXmlFirstChartPlotElement(sceneChart, chartXml, PptxSceneChartPlotKind.Bar);
        if (barChart is null)
        {
            return fallbackBaselineY;
        }

        PptxSceneChartPlot? barPlot = ReadSceneChartPlot(sceneChart, PptxSceneChartPlotKind.Bar, 0);
        ChartBarPlotOptions barOptions = ReadSceneOrXmlChartBarOptions(barPlot, barChart, PptxSceneChartGrouping.Clustered);
        bool horizontalBars = barOptions.BarDirection == PptxSceneChartBarDirection.Bar;
        ChartLayout layout = GetBarChartLayout(document, theme, bounds, chartXml, sceneChart, colorMap, barPlot, barChart, barOptions, workbook, plotVisibleOnly, fontResolver);
        ChartPlotBox titleAnchorBox = layout.PlotBox;
        if (horizontalBars && layout.ManualPlotLayoutApplied && IsAutoGeneratedChartTitle(sceneChart))
        {
            ChartFrameBox frame = GetChartFrameBox(document, bounds);
            ChartLegendLayout legend = ReadSceneOrXmlChartLegendLayout(theme, colorMap, sceneChart, chartXml);
            titleAnchorBox = GetBarChartPlotLayout(
                theme,
                colorMap,
                frame,
                chartXml,
                sceneChart,
                barPlot,
                barChart,
                ReadSceneOrXmlChartTitleText(sceneChart, chartXml),
                legend,
                barOptions,
                workbook,
                plotVisibleOnly,
                ignoreManualPlotLayout: true,
                fontResolver: fontResolver).PlotBox;
        }

        double offsetFactor = !horizontalBars && IsAutoGeneratedChartTitle(sceneChart)
            ? PptxChartMetricRules.AutoBarTitleAbovePlotBaselineOffsetFactor
            : PptxChartMetricRules.TitleAbovePlotBaselineOffsetFactor;
        return titleAnchorBox.Y + titleAnchorBox.Height + fontSize * offsetFactor;
    }

    private static bool IsAutoGeneratedChartTitle(PptxSceneChart? sceneChart)
    {
        return sceneChart?.Title.IsAutoGenerated == true;
    }

    private static ChartTextStyle ReadSceneOrXmlChartTitleTextStyle(PptxTheme theme, PptxColorMap colorMap, PptxSceneChart? sceneChart, XDocument chartXml, bool isAutoTitle)
    {
        if (sceneChart is null)
        {
            XElement? title = ReadChartTitleElement(chartXml);
            return ResolveAutoChartTitleTextStyle(
                ReadChartTextStyle(theme, colorMap, chartXml, title, fallbackFontSize: PptxChartMetricRules.TitleFallbackFontSize),
                ChartTextStyleOverride.Empty,
                isAutoTitle);
        }

        ChartTextStyle style = CreateDefaultChartTextStyle(theme, sceneChart.ColorMap, fallbackFontSize: PptxChartMetricRules.TitleFallbackFontSize);
        style = style.Merge(ToChartTextStyleOverride(PptxSceneBuilder.ResolveChartTitleTextStyleOverride(sceneChart)));
        ChartTextStyleOverride titleStyle = ToChartTextStyleOverride(sceneChart.Title.TextStyle);
        return ResolveAutoChartTitleTextStyle(style, titleStyle, isAutoTitle);
    }

    private static ChartTextStyle ResolveAutoChartTitleTextStyle(ChartTextStyle style, ChartTextStyleOverride titleStyle, bool isAutoTitle)
    {
        if (!isAutoTitle)
        {
            return style;
        }

        return style with
        {
            FontSize = titleStyle.FontSize is null
                ? style.FontSize * PptxChartMetricRules.AutoTitleFontScale
                : style.FontSize,
            Bold = true
        };
    }

    private static string? ReadSceneOrXmlChartTitleText(PptxSceneChart? sceneChart, XDocument chartXml)
    {
        if (sceneChart is not null)
        {
            if (sceneChart.Title.IsAutoDeleted == true)
            {
                return null;
            }

            return sceneChart.Title.Text;
        }

        return ReadChartTitleText(chartXml);
    }

    private static PptxSceneChartTextBodyProperties ReadSceneOrXmlChartTitleTextBodyProperties(PptxSceneChart? sceneChart, XDocument chartXml)
    {
        if (sceneChart is not null)
        {
            return sceneChart.Title.TextBodyProperties;
        }

        XElement? title = ReadChartTitleElement(chartXml);
        return PptxSceneBuilder.ReadChartTextBodyProperties(title);
    }

    private static IReadOnlyList<ChartTextRunOverride> ReadSceneOrXmlChartTitleTextRuns(PptxTheme theme, PptxColorMap colorMap, PptxSceneChart? sceneChart, XDocument chartXml)
    {
        if (sceneChart is not null)
        {
            if (sceneChart.Title.IsAutoGenerated)
            {
                return [];
            }

            return ToChartTextRuns(sceneChart.Title.TextRuns);
        }

        XElement? titleText = ReadChartTitleElement(chartXml)?.Element(ChartNamespace + "tx");
        return ToChartTextRuns(PptxSceneBuilder.ReadChartTextRuns(titleText, theme, colorMap));
    }

    private static string? ReadChartTitleText(XDocument chartXml)
    {
        XElement? title = ReadChartTitleElement(chartXml);
        if (title is null)
        {
            return null;
        }

        string text = string.Concat(title
            .Descendants(DrawingNamespace + "t")
            .Select(element => (string?)element)
            .Where(value => !string.IsNullOrEmpty(value)));
        if (!string.IsNullOrWhiteSpace(text))
        {
            return text;
        }

        return (string?)title
            .Descendants(ChartNamespace + "v")
            .FirstOrDefault();
    }

    private static XElement? ReadChartTitleElement(XDocument chartXml)
    {
        return chartXml.Descendants(ChartNamespace + "title").FirstOrDefault();
    }

    private static ChartIndexedTextVector ReadChartCategoryLabelVector(XElement chartElement, ChartWorkbookData? workbook, bool plotVisibleOnly)
    {
        XElement? categories = chartElement
            .Element(ChartNamespace + "ser")
            ?.Element(ChartNamespace + "cat");
        if (categories is null)
        {
            return default;
        }

        XElement? cache = categories
            .Descendants(ChartNamespace + "strCache")
            .Concat(categories.Descendants(ChartNamespace + "strLit"))
            .Concat(categories.Descendants(ChartNamespace + "numCache"))
            .Concat(categories.Descendants(ChartNamespace + "numLit"))
            .Concat(categories.Descendants(ChartNamespace + "multiLvlStrCache"))
            .FirstOrDefault();
        PptxSceneChartDataSource source = PptxSceneBuilder.ReadChartDataSource(categories, "strRef", "numRef", "multiLvlStrRef");
        if (cache is null)
        {
            return new ChartIndexedTextVector(
                [],
                null,
                [],
                source.Formula,
                source,
                ReadWorkbookTextPoints(workbook, source),
                plotVisibleOnly);
        }

        IEnumerable<XElement> pointElements = cache.Name.LocalName == "multiLvlStrCache"
            ? cache.Descendants(ChartNamespace + "pt")
            : cache.Elements(ChartNamespace + "pt");
        ChartIndexedTextPoint[] points = ReadChartIndexedTextPoints(pointElements);
        IReadOnlyList<IReadOnlyList<ChartIndexedTextPoint>> levels = cache.Name.LocalName == "multiLvlStrCache"
            ? cache
                .Elements(ChartNamespace + "lvl")
                .Select(level => ReadChartIndexedTextPoints(level.Elements(ChartNamespace + "pt")))
                .Where(level => level.Length != 0)
                .ToArray()
            : [];
        return new ChartIndexedTextVector(
            points,
            PptxSceneBuilder.ReadChartCachePointCount(cache).Value ?? InferPointCount(points),
            levels,
            source.Formula,
            source,
            ReadWorkbookTextPoints(workbook, source),
            plotVisibleOnly);
    }

    private static ChartIndexedTextPoint[] ReadChartIndexedTextPoints(IEnumerable<XElement> sourcePoints)
    {
        return PptxSceneBuilder
            .ReadChartStringPoints(sourcePoints, requireNonNegativeIndex: true)
            .Select(point => ToChartIndexedTextPoint(point, trimText: true))
            .ToArray();
    }
}
