using System.Globalization;
using System.Xml.Linq;
using Lokad.OoxPdf.Ooxml;
using static Lokad.OoxPdf.Ooxml.OoxNamespaces;

namespace Lokad.OoxPdf.Pptx;

internal sealed record PptxTextRunSnapshot(
    string Text,
    double X,
    double Y,
    double Width,
    double FontSize,
    double CharacterSpacing,
    RgbColor Color,
    double Alpha,
    RgbColor? Highlight,
    bool Bold,
    bool Italic,
    bool Underline,
    bool Strike,
    string Alignment,
    string? FontFamily);

internal sealed record PptxTextFrameModelSnapshot(
    double FrameX,
    double FrameY,
    double FrameWidth,
    double FrameHeight,
    double TextX,
    double TextWidth,
    double TextWrapWidth,
    double TextHeight,
    int? TableRowIndex,
    int? TableColumnIndex,
    int? TableRowSpan,
    int? TableColumnSpan,
    double? TableDeclaredRowHeight,
    double? TableDeclaredRowSpanHeight,
    double? TableDeclaredHeight,
    double? TableHeightSlackFactor,
    double VerticalOffset,
    double InsetLeft,
    double InsetRight,
    double InsetTop,
    double InsetBottom,
    string? InsetLeftValue,
    string? InsetRightValue,
    string? InsetTopValue,
    string? InsetBottomValue,
    double FontScale,
    string? FontScaleValue,
    string FontScaleSource,
    double LineSpacingScale,
    string? LineSpacingReductionValue,
    string LineSpacingScaleSource,
    bool CompatibleLineSpacing,
    string? CompatibleLineSpacingValue,
    string CompatibleLineSpacingSource,
    double? RotationDegrees,
    string? RotationValue,
    string RotationDegreesSource,
    int InheritedPlaceholderCount,
    bool HasInheritedTextBody,
    bool UsesInheritedShapeBounds,
    string InsetLeftSource,
    string InsetRightSource,
    string InsetTopSource,
    string InsetBottomSource,
    string Orientation,
    string? OrientationValue,
    string OrientationSource,
    string VerticalAnchor,
    string? VerticalAnchorValue,
    string VerticalAnchorSource,
    bool? AnchorCenter,
    string? AnchorCenterValue,
    string AnchorCenterSource,
    string WrapMode,
    string? WrapValue,
    string WrapSource,
    string VerticalOverflow,
    string? VerticalOverflowValue,
    string VerticalOverflowSource,
    int ColumnCount,
    double ColumnSpacing,
    string ColumnSource,
    string ColumnCountSource,
    string ColumnSpacingSource,
    string? ColumnCountValue,
    string? ColumnSpacingValue,
    string AutofitModeValue,
    string AutofitModeSource,
    IReadOnlyList<PptxTextParagraphModelSnapshot> Paragraphs);

internal sealed record PptxTextParagraphModelSnapshot(
    int Level,
    bool HasEndParagraphProperties,
    double EndParagraphFontSize,
    string? EndParagraphTypeface,
    bool EndParagraphBold,
    bool EndParagraphItalic,
    double EmptySpacingBefore,
    double EmptySpacingAfter,
    bool HasLayoutContent,
    bool HasVisibleContent,
    bool HasManualLineBreak,
    double FirstLineFallbackFontSize,
    string CascadeLevelName,
    int ResolvedCascadeSourceCount,
    IReadOnlyList<string> CascadeLayerNames,
    IReadOnlyList<string> CascadeLayerKinds,
    int ResolvedStyleSourceCount,
    IReadOnlyList<string> ResolvedStyleLayerNames,
    IReadOnlyList<string> ResolvedStyleLayerKinds,
    string Alignment,
    string? AlignmentValue,
    double FontSize,
    string BulletKind,
    string? BulletCharacter,
    string? BulletResolvedCharacter,
    string? BulletAutoNumberType,
    string? BulletAutoNumberStartAtValue,
    string? BulletFontTypeface,
    string? BulletFontCharset,
    string? BulletResolvedFontTypeface,
    string BulletFontTypefaceSource,
    string? BulletColor,
    string BulletSizeKind,
    string? BulletSizeValue,
    double SpacingBefore,
    double SpacingAfter,
    double LineSpacingValue,
    string LineSpacingKind,
    bool LineSpacingUseNormalLineAdvance,
    double MarginLeft,
    double HangingIndent,
    IReadOnlyList<double> TabStops,
    IReadOnlyList<PptxTextRunModelSnapshot> Runs);

internal sealed record PptxTextRunModelSnapshot(
    int RunIndex,
    string Kind,
    string Text,
    int ResolvedCascadeSourceCount,
    IReadOnlyList<string> CascadeLayerNames,
    IReadOnlyList<string> CascadeLayerKinds,
    double FontSize,
    double CharacterSpacing,
    string? Typeface,
    string TypefaceSource,
    string ColorSource,
    bool HasHyperlinkClick,
    string? HyperlinkClickId,
    bool Underline,
    string? UnderlineValue,
    bool Strike,
    string? StrikeValue,
    string? CapsValue,
    RgbColor? Highlight);

internal sealed record PptxTextFlowSnapshot(IReadOnlyList<PptxTextFlowFrameSnapshot> Frames);

internal sealed record PptxTextFlowFrameSnapshot(
    double TextX,
    double TextWidth,
    double TextHeight,
    double ClipY,
    double ClipHeight,
    double CursorTop,
    IReadOnlyList<PptxTextFlowParagraphSnapshot> Paragraphs);

internal sealed record PptxTextFlowParagraphSnapshot(
    int Level,
    string Alignment,
    double FontSize,
    IReadOnlyList<PptxTextFlowRunSnapshot> Runs);

internal sealed record PptxTextFlowRunSnapshot(
    string SourceKind,
    string SourceText,
    double FontSize,
    string? Typeface,
    bool HasHyperlinkClick,
    string? HyperlinkClickId,
    IReadOnlyList<PptxTextFlowSegmentSnapshot> Segments);

internal sealed record PptxTextFlowSegmentSnapshot(
    string Kind,
    string Text,
    string AdvanceText,
    bool Draw,
    bool PreventCoalesce,
    double FontScale);

internal sealed record PptxTextLayoutSnapshot(IReadOnlyList<PptxTextFrameLayoutSnapshot> Frames);

internal sealed record PptxTextFrameLayoutSnapshot(IReadOnlyList<PptxTextParagraphLayoutSnapshot> Paragraphs);

internal sealed record PptxTextParagraphLayoutSnapshot(
    int Level,
    IReadOnlyList<PptxTextLineLayoutSnapshot> Lines);

internal sealed record PptxTextLineLayoutSnapshot(
    double TopY,
    double BaselineY,
    double Advance,
    double BaselineOffset,
    double MaxFontSize,
    string LineSpacingKind,
    PptxTextBaselineMetricSnapshot BaselineMetric,
    double StartX,
    double EndX,
    double NaturalEndX,
    string Alignment,
    IReadOnlyList<PptxTextSpanLayoutSnapshot> Spans);

internal sealed record PptxTextBaselineMetricSnapshot(
    string Source,
    string? Typeface,
    bool Bold,
    bool Italic,
    double FontSize,
    double Ratio,
    int UnitsPerEm,
    int WindowsAscender,
    int WindowsDescender,
    int TypographicAscender,
    int TypographicDescender,
    int TypographicLineGap);

internal sealed record PptxTextSpanLayoutSnapshot(
    string? SourceText,
    string Text,
    double X,
    double Y,
    double Width,
    double FontSize,
    IReadOnlyList<PptxTextAtomLayoutSnapshot> Atoms,
    PptxTextGlyphSpanLayoutSnapshot GlyphSpan);

internal sealed record PptxTextGlyphSpanLayoutSnapshot(
    string Text,
    string? Typeface,
    double FontSize,
    double LeadingAdjustment,
    double NaturalWidth,
    double LayoutWidth,
    int GlyphCount,
    double FirstAdjustmentAfterOrigin,
    int InterGlyphAdjustmentCount,
    double InterGlyphAdjustmentSum,
    double InterGlyphAdjustmentMin,
    double InterGlyphAdjustmentMax,
    double InterGlyphAdjustmentAverage,
    IReadOnlyList<PptxTextGlyphLayoutSnapshot> Glyphs);

internal sealed record PptxTextGlyphLayoutSnapshot(
    int CodePoint,
    string? Typeface,
    string TypefaceResolutionSource,
    ushort GlyphId,
    double Advance,
    double AdjustmentBefore);

internal sealed record PptxTextAtomLayoutSnapshot(
    string Kind,
    string Text,
    double X,
    double Width,
    bool Draw);

internal sealed record PptxTextGlyphRunSnapshot(
    string Text,
    double X,
    double BaselineY,
    double Width,
    double NaturalWidth,
    double LayoutWidth,
    string? FontFamily,
    string ResolvedFontFamily,
    bool ResolvedFontIsFallback,
    bool ResolvedFontBold,
    bool ResolvedFontItalic,
    int ResolvedFontWeightClass,
    int ResolvedFontFaceIndex,
    bool ResolvedFontHasMathTable,
    bool ResolvedFontHasGposTable,
    bool ResolvedFontHasKernTable,
    int ResolvedFontUnitsPerEm,
    int ResolvedFontGlyphCount,
    int ResolvedFontOs2Version,
    int ResolvedFontOs2WidthClass,
    int ResolvedFontOs2TypographicAscender,
    int ResolvedFontOs2TypographicDescender,
    int ResolvedFontOs2TypographicLineGap,
    int ResolvedFontOs2WindowsAscender,
    int ResolvedFontOs2WindowsDescender,
    double ResolvedFontPostItalicAngle,
    int ResolvedFontPostUnderlinePosition,
    int ResolvedFontPostUnderlineThickness,
    bool ResolvedFontPostIsFixedPitch,
    bool Bold,
    bool Italic,
    bool Underline,
    bool Strike,
    bool SyntheticBold,
    bool SyntheticItalic,
    RgbColor? HighlightColor,
    double? HighlightX,
    double? HighlightY,
    double? HighlightWidth,
    double? HighlightHeight,
    double? UnderlineX,
    double? UnderlineY,
    double? UnderlineWidth,
    double? UnderlineHeight,
    double? StrikeX,
    double? StrikeY,
    double? StrikeWidth,
    double? StrikeHeight,
    int FrameIndex,
    int ParagraphIndex,
    int? SourceRunIndex,
    string ParagraphBulletKind,
    string? ParagraphAutoNumberType,
    int? ParagraphAutoNumberStartAt,
    int LineIndex,
    int SpanIndex,
    int LineSpanCount,
    double FrameFontScale,
    double FrameShapeX,
    double FrameShapeTopY,
    double FrameShapeWidth,
    double FrameShapeHeight,
    int? TableRowIndex,
    int? TableColumnIndex,
    int? TableRowSpan,
    int? TableColumnSpan,
    double FrameInsetLeft,
    double FrameInsetRight,
    double FrameInsetTop,
    double FrameInsetBottom,
    string FrameWrapMode,
    string? FrameWrapValue,
    string FrameVerticalOverflowMode,
    string? FrameVerticalOverflowValue,
    string FrameVerticalOverflowSource,
    string FrameAutofitMode,
    double FrameTextX,
    double FrameTextWidth,
    double FrameTextWrapWidth,
    double FrameTextHeight,
    double FrameClipX,
    double FrameClipWidth,
    double FrameClipY,
    double FrameClipHeight,
    int FrameColumnCount,
    double FrameColumnSpacing,
    double LineTopY,
    double LineAdvance,
    double LineMaxFontSize,
    double LayoutFontSize,
    double PdfFontSize,
    double LayoutCharacterSpacing,
    double PdfCharacterSpacing,
    int GlyphCount,
    double FirstAdjustmentAfterOrigin,
    int InterGlyphAdjustmentCount,
    double InterGlyphAdjustmentSum,
    double InterGlyphAdjustmentMin,
    double InterGlyphAdjustmentMax,
    double InterGlyphAdjustmentAverage,
    IReadOnlyList<PptxTextGlyphRunAtomSnapshot> Glyphs);

internal sealed record PptxTextGlyphRunAtomSnapshot(
    int CodePoint,
    string? Typeface,
    string TypefaceResolutionSource,
    string ResourceName,
    ushort GlyphId,
    double Advance,
    double AdjustmentBefore);
