namespace Lokad.OoxPdf.Docx;

internal sealed record DocxStructureBlockSnapshot(
    int Index,
    string Kind,
    string? PreviousKind,
    string? NextKind,
    string? ParagraphStyleId,
    bool? ParagraphStyleFound,
    int? ParagraphStyleDepth,
    bool? HasDocumentDefaultParagraphProperties,
    bool? HasDirectParagraphProperties,
    bool? HasTableStyleParagraphProperties,
    int RunCount,
    int TextLength,
    bool HasVisibleText,
    int RevisionCount,
    int InsertionRevisionCount,
    int DeletionRevisionCount,
    int MoveFromRevisionCount,
    int MoveToRevisionCount,
    int OtherRevisionCount,
    int RevisionRangeCount,
    string? ListFormatValue,
    int InlineImageCount,
    int InlineReferenceCount,
    int AnchoredInlineReferenceCount,
    int ResolvedInlineReferenceCount,
    int MaxInlineReferenceTextOffsetInRun,
    int CommentReferenceCount,
    int FootnoteReferenceCount,
    int EndnoteReferenceCount,
    int FieldReferenceCount,
    int PageFieldReferenceCount,
    int NumPagesFieldReferenceCount,
    int OtherFieldReferenceCount,
    int ComplexFieldReferenceCount,
    int CachedResultFieldReferenceCount,
    int RenderedCachedResultFieldReferenceCount,
    int PlaceholderFieldReferenceCount,
    int NestedFieldReferenceCount,
    int BookmarkAnchorCount,
    int HyperlinkCount,
    int ExternalHyperlinkCount,
    int InternalHyperlinkCount,
    int TableRowCount,
    int? TableIndex,
    double? SpacingBeforePoints,
    double? SpacingAfterPoints,
    double? LineSpacingPoints,
    double? LineSpacingFactor,
    bool HasBeforeSpacingToken,
    bool HasAfterSpacingToken,
    string? BeforeAutoSpacingValue,
    string? AfterAutoSpacingValue,
    bool? ContextualSpacing,
    bool? KeepNext,
    bool? KeepLines,
    bool? WidowControl,
    bool? WordWrap,
    string? WordWrapValue,
    int? TableMaxColumnCount,
    double? TablePreferredWidthPoints,
    string? TablePreferredWidthType,
    double? TableIndentPoints,
    double? TableCellSpacingPoints,
    string? TableLayoutValue,
    string? PageBreakSourceKind,
    string? PageBreakValue,
    string? ManualBreakSourceKind,
    string? ManualBreakValue,
    string? ImplicitSourceKind,
    string? SectionBreakTypeValue,
    string? SectionColumnCountValue,
    string? SectionColumnEqualWidthValue,
    string? SectionColumnSpaceValue,
    int? SectionColumnDefinitionCount,
    int? SectionColumnDefinitionWidthTokenCount,
    int? SectionColumnDefinitionSpaceTokenCount,
    double? ParagraphIndentLeftPoints,
    double? ParagraphIndentRightPoints,
    double? ParagraphIndentFirstLinePoints,
    double? ParagraphIndentHangingPoints,
    int? WhitespaceDelimitedTokenCount,
    int? LongestWhitespaceDelimitedTokenLength,
    int? SpaceCharacterCount,
    int? NonAsciiCharacterCount,
    int? PunctuationCharacterCount,
    int? DigitCharacterCount,
    int? UppercaseCharacterCount,
    int? LowercaseCharacterCount,
    int? TabStopCount,
    bool? SnapToGrid,
    string? SnapToGridValue,
    bool? PageBreakConsumesParagraphLine,
    double? PageBreakLineSpacingPoints,
    double? PageBreakLineSpacingFactor,
    bool? ManualBreakConsumesParagraphLine,
    double? ManualBreakLineSpacingPoints,
    double? ManualBreakLineSpacingFactor)
{
    public static DocxStructureBlockSnapshot ForUnknown(
        int blockIndex,
        string? previousKind,
        string? nextKind)
    {
        return new DocxStructureBlockSnapshot(
            blockIndex,
            "Unknown",
            previousKind,
            nextKind,
            null,
            null,
            null,
            null,
            null,
            null,
            0,
            0,
            false,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        );
    }

    public static DocxStructureBlockSnapshot ForImplicitParagraph(
        int blockIndex,
        string? previousKind,
        string? nextKind,
        DocxImplicitParagraphElement implicitParagraph)
    {
        return new DocxStructureBlockSnapshot(
            blockIndex,
            "ImplicitParagraph",
            previousKind,
            nextKind,
            null,
            null,
            null,
            null,
            null,
            null,
            0,
            0,
            false,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            implicitParagraph.SourceKind.ToValueString(),
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        );
    }

    public static DocxStructureBlockSnapshot ForPageBreak(
        int blockIndex,
        string? previousKind,
        string? nextKind,
        DocxPageBreakElement pageBreak)
    {
        return new DocxStructureBlockSnapshot(
            blockIndex,
            "PageBreak",
            previousKind,
            nextKind,
            null,
            null,
            null,
            null,
            null,
            null,
            0,
            0,
            false,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            pageBreak.SourceKind.ToValueString(),
            pageBreak.Value,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            pageBreak.BreakParagraph is not null,
            pageBreak.BreakParagraph?.EffectiveProperties.LineSpacingPoints,
            pageBreak.BreakParagraph?.EffectiveProperties.LineSpacingFactor,
            null,
            null,
            null
        );
    }

    public static DocxStructureBlockSnapshot ForManualBreak(
        int blockIndex,
        string? previousKind,
        string? nextKind,
        DocxManualBreakElement manualBreak)
    {
        return new DocxStructureBlockSnapshot(
            blockIndex,
            "ManualBreak",
            previousKind,
            nextKind,
            null,
            null,
            null,
            null,
            null,
            null,
            0,
            0,
            false,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            manualBreak.SourceKind.ToValueString(),
            manualBreak.Value,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            manualBreak.BreakParagraph is not null,
            manualBreak.BreakParagraph?.EffectiveProperties.LineSpacingPoints,
            manualBreak.BreakParagraph?.EffectiveProperties.LineSpacingFactor
        );
    }

    public static DocxStructureBlockSnapshot ForSectionBreak(
        int blockIndex,
        string? previousKind,
        string? nextKind,
        int revisionCount,
        int insertionRevisionCount,
        int deletionRevisionCount,
        int moveFromRevisionCount,
        int moveToRevisionCount,
        int otherRevisionCount,
        DocxSectionBreakType? typeValue,
        string? columnCountValue,
        string? columnEqualWidthValue,
        string? columnSpaceValue,
        int? definitionCount,
        int? widthTokenCount,
        int? spaceTokenCount)
    {
        return new DocxStructureBlockSnapshot(
            blockIndex,
            "SectionBreak",
            previousKind,
            nextKind,
            null,
            null,
            null,
            null,
            null,
            null,
            0,
            0,
            false,
            revisionCount,
            insertionRevisionCount,
            deletionRevisionCount,
            moveFromRevisionCount,
            moveToRevisionCount,
            otherRevisionCount,
            0,
            null,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            0,
            null,
            null,
            null,
            null,
            null,
            false,
            false,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            typeValue?.ToValueString(),
            columnCountValue,
            columnEqualWidthValue,
            columnSpaceValue,
            definitionCount,
            widthTokenCount,
            spaceTokenCount,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null
        );
    }

};

internal sealed record DocxStructureStorySnapshot(
    string Kind,
    string Scope,
    int? SectionBreakBlockIndex,
    string? VariantType,
    int BlockCount,
    int ParagraphCount,
    int TableCount,
    int TextLength,
    int RevisionCount,
    int InsertionRevisionCount,
    int DeletionRevisionCount,
    int MoveFromRevisionCount,
    int MoveToRevisionCount,
    int OtherRevisionCount,
    int InlineImageCount,
    int InlineReferenceCount,
    int CommentReferenceCount,
    int ResolvedInlineReferenceCount,
    int FieldReferenceCount,
    int ComplexFieldReferenceCount,
    int CachedResultFieldReferenceCount,
    int RenderedCachedResultFieldReferenceCount,
    int PlaceholderFieldReferenceCount,
    int NestedFieldReferenceCount,
    int BookmarkAnchorCount,
    int HyperlinkCount,
    int ExternalHyperlinkCount,
    int InternalHyperlinkCount,
    int FloatingDrawingCount,
    bool HasCommentAuthor,
    bool HasCommentInitials,
    bool HasCommentDate,
    string? CommentParagraphId,
    string? CommentParentParagraphId,
    string? CommentParentId,
    bool? CommentResolved);

internal sealed record DocxStructureInlineReferenceSnapshot(
    int SourceBlockIndex,
    string SourceBlockKind,
    int SourceParagraphIndex,
    string Kind,
    string? Id,
    string? CustomMarkFollowsValue,
    string? DisplayText,
    int SourceRunIndex,
    int RunChildIndex,
    int TextOffsetInRun,
    int? ResolvedStoryIndex,
    string? ResolvedStoryKind,
    string? ResolvedStoryPartName,
    string? ResolvedStoryId,
    int? ResolvedStoryBlockCount,
    int? ResolvedStoryTextLength,
    int RevisionCount,
    string? RevisionKind,
    string? RevisionSourceElement);

internal sealed record DocxStructureCommentRangeSnapshot(
    int SourceBlockIndex,
    string SourceBlockKind,
    int SourceParagraphIndex,
    string? Id,
    int? StartSourceRunIndex,
    int? StartTextOffset,
    int? EndSourceRunIndex,
    int? EndTextOffset,
    int? ReferenceSourceRunIndex,
    int? ReferenceTextOffset,
    int? ResolvedStoryIndex,
    string? ResolvedStoryPartName,
    string? ResolvedStoryId,
    int? ResolvedStoryBlockCount,
    int? ResolvedStoryTextLength);

internal sealed record DocxStructureCommentStoryAnchorSnapshot(
    string? Id,
    string Status,
    bool HasPackageAnchor,
    bool HasHiddenAnchor,
    int VisibleInlineReferenceCount,
    int VisibleRangeCount);

internal sealed record DocxStructureRevisionRangeSnapshot(
    int SourceBlockIndex,
    string SourceBlockKind,
    int SourceParagraphIndex,
    string Kind,
    string? Id,
    bool HasName,
    bool HasAuthor,
    bool HasDate,
    int? StartSourceRunIndex,
    int? StartTextOffset,
    int? EndSourceRunIndex,
    int? EndTextOffset,
    bool IsClosed)
{
    public bool IsLinkedAcrossBlocks { get; init; }
    public int? LinkedSourceBlockIndex { get; init; }
    public int? LinkedSourceParagraphIndex { get; init; }
}

internal sealed record DocxStructureFormattingRevisionPropertySnapshot(
    string Family,
    string SourceElement,
    string PropertyElementName,
    int Count);

internal sealed record DocxStructureFloatingDrawingSnapshot(
    int Index,
    string? WrapKind,
    string? WrapTextValue,
    string? BehindDocumentValue,
    string? LayoutInCellValue,
    string? AllowOverlapValue,
    string? HorizontalRelativeFromValue,
    string? HorizontalAlignValue,
    string? HorizontalOffsetValue,
    string? VerticalRelativeFromValue,
    string? VerticalAlignValue,
    string? VerticalOffsetValue,
    string? ExtentCxValue,
    string? ExtentCyValue,
    string? DistanceTopValue,
    string? DistanceBottomValue,
    string? DistanceLeftValue,
    string? DistanceRightValue,
    string? SimplePositionValue,
    string? RelativeHeightValue,
    string? LockedValue,
    string? ImageRelationshipId,
    string? ImagePartName,
    string? ImageContentType,
    double? ImageWidthPoints,
    double? ImageHeightPoints,
    int? SourceParagraphIndex,
    int? SourceBlockIndex,
    int TextBoxBlockCount,
    int TextBoxParagraphCount,
    int TextBoxTextLength,
    int RevisionCount,
    int InsertionRevisionCount,
    int DeletionRevisionCount,
    int MoveFromRevisionCount,
    int MoveToRevisionCount,
    int OtherRevisionCount);

internal sealed record DocxStructureStyleUsageSnapshot(
    string Kind,
    string? StyleId,
    int Count,
    int ParagraphCount,
    int TableCount,
    int TextLength,
    int BeforeSpacingTokenParagraphCount,
    int AfterSpacingTokenParagraphCount,
    int BeforeAutoSpacingParagraphCount,
    int AfterAutoSpacingParagraphCount,
    int BeforeLinesSpacingParagraphCount,
    int AfterLinesSpacingParagraphCount,
    int ContextualSpacingParagraphCount,
    int ExactLineSpacingParagraphCount,
    int AtLeastLineSpacingParagraphCount,
    int AutoLineSpacingParagraphCount,
    int TableStyleParagraphPropertiesCount);

internal sealed record DocxStructureListUsageSnapshot(
    string NumberId,
    int Level,
    string FormatValue,
    string SuffixValue,
    int ParagraphCount,
    int TextLength,
    int LeftIndentParagraphCount,
    int RightIndentParagraphCount,
    int FirstLineIndentParagraphCount,
    int HangingIndentParagraphCount,
    int NumberingTabParagraphCount,
    int ParagraphIndentOverrideCount,
    int ParagraphNumberingTabStopCount);

internal sealed record DocxStructureTableSnapshot(
    int TableIndex,
    int BlockIndex,
    string? StyleId,
    int RowCount,
    int MaxColumnCount,
    int GridColumnCount,
    double GridColumnsWidthSum,
    bool HasExplicitGrid,
    double? PreferredWidthPoints,
    string? PreferredWidthValue,
    string? PreferredWidthType,
    double? IndentPoints,
    string? IndentValue,
    string? IndentType,
    double? CellSpacingPoints,
    string? CellSpacingValue,
    string? CellSpacingType,
    string? LayoutValue,
    int HeaderRowCount,
    int CantSplitRowCount,
    int DeclaredHeightRowCount,
    int ExactHeightRowCount,
    int AtLeastHeightRowCount,
    int RowPropertyExceptionCount,
    int CellCount,
    int GridSpanCellCount,
    int VerticalMergeCellCount,
    int VerticalMergeRestartCellCount,
    int ShadedCellCount,
    int VerticalAlignmentCellCount,
    int PreferredWidthCellCount,
    int VisibleBorderCount,
    int SingleBorderCount,
    int ThickBorderCount,
    int DoubleBorderCount,
    int DottedBorderCount,
    int DashedBorderCount,
    int SuppressedBorderCount,
    int OtherBorderStyleCount,
    int ParagraphCount,
    int RunCount,
    int TextLength,
    int RevisionCount,
    int InsertionRevisionCount,
    int DeletionRevisionCount,
    int MoveFromRevisionCount,
    int MoveToRevisionCount,
    int OtherRevisionCount,
    int WhitespaceDelimitedTokenCount,
    int LongestWhitespaceDelimitedTokenLength,
    int InlineImageCount,
    int InlineReferenceCount,
    int HyperlinkCount,
    int ExternalHyperlinkCount,
    int InternalHyperlinkCount,
    int NumberedParagraphCount,
    int KeepRuleParagraphCount,
    bool? LookFirstRow,
    bool? LookFirstColumn,
    bool? LookNoHorizontalBand,
    bool? LookNoVerticalBand,
    IReadOnlyList<DocxStructureTableRowSnapshot> Rows);

internal sealed record DocxStructureTableRowSnapshot(
    int RowIndex,
    int CellCount,
    int LogicalGridSpan,
    bool IsHeader,
    string? HeaderValue,
    bool CantSplit,
    string? CantSplitValue,
    double? HeightPoints,
    string? HeightValue,
    string? HeightRuleValue,
    bool HasTablePropertyExceptionCellMargins,
    int GridSpanCellCount,
    int VerticalMergeCellCount,
    int VerticalMergeRestartCellCount,
    int ShadedCellCount,
    int VerticalAlignmentCellCount,
    int PreferredWidthCellCount,
    int VisibleBorderCount,
    int ParagraphCount,
    int RunCount,
    int TextLength,
    int RevisionCount,
    int InsertionRevisionCount,
    int DeletionRevisionCount,
    int MoveFromRevisionCount,
    int MoveToRevisionCount,
    int OtherRevisionCount,
    int WhitespaceDelimitedTokenCount,
    int LongestWhitespaceDelimitedTokenLength,
    int InlineImageCount,
    int InlineReferenceCount,
    int HyperlinkCount,
    int ExternalHyperlinkCount,
    int InternalHyperlinkCount,
    int NumberedParagraphCount,
    int KeepRuleParagraphCount,
    int BeforeSpacingTokenParagraphCount,
    int AfterSpacingTokenParagraphCount,
    double MaxFontSize,
    IReadOnlyList<DocxStructureTableCellSnapshot> Cells);

internal sealed record DocxStructureTableCellSnapshot(
    int CellIndex,
    int GridSpan,
    string? GridSpanValue,
    bool HasVerticalMerge,
    string? VerticalMergeValue,
    bool HasShading,
    string? ShadingValue,
    string? VerticalAlignmentValue,
    bool HasPreferredWidth,
    double? PreferredWidthPoints,
    string? PreferredWidthValue,
    string? PreferredWidthType,
    int VisibleBorderCount,
    int ParagraphCount,
    int RunCount,
    int TextLength,
    int RevisionCount,
    int InsertionRevisionCount,
    int DeletionRevisionCount,
    int MoveFromRevisionCount,
    int MoveToRevisionCount,
    int OtherRevisionCount,
    int WhitespaceDelimitedTokenCount,
    int LongestWhitespaceDelimitedTokenLength,
    int InlineImageCount,
    int InlineReferenceCount,
    int HyperlinkCount,
    int ExternalHyperlinkCount,
    int InternalHyperlinkCount,
    int NumberedParagraphCount,
    int KeepRuleParagraphCount,
    int BeforeSpacingTokenParagraphCount,
    int AfterSpacingTokenParagraphCount,
    double MaxFontSize,
    int SpaceCharacterCount,
    int NonAsciiCharacterCount,
    int PunctuationCharacterCount,
    int DigitCharacterCount,
    int UppercaseCharacterCount,
    int LowercaseCharacterCount,
    int BodyElementCount,
    int ManualBreakElementCount,
    int PageBreakElementCount,
    int NestedTableElementCount);

internal sealed record DocxStructureTableAdjacencySnapshot(
    int TableIndex,
    int BlockIndex,
    string? PreviousKind,
    string? NextKind,
    int RowCount,
    int MaxColumnCount,
    string? PreviousParagraphStyleId,
    double? PreviousParagraphSpacingAfterPoints,
    bool? PreviousParagraphHasAfterSpacingToken,
    string? NextParagraphStyleId,
    double? NextParagraphSpacingBeforePoints,
    bool? NextParagraphHasBeforeSpacingToken,
    int? NextParagraphTextLength,
    bool? NextParagraphHasListLabel,
    bool? NextParagraphKeepNext,
    bool? NextParagraphKeepLines);
